select * from customer_shopping_behavior limit 20

-- 1. what is the total revenue generated by male and female customer ?
select gender , sum(purchase_amount_usd) as revenue 
from customer_shopping_behavior
group by gender

--2. which customers used a discount but still spent more than the average purchase amount ?
select customer_id , purchase_amount_usd 
from customer_shopping_behavior
where discount_applied = 'Yes' and purchase_amount_usd >= (select avg(purchase_amount_usd)
                                                    from customer_shopping_behavior)

--3. which are the top 5 products with the highest average review rating ?
select item_purchased , round(avg(review_rating)::numeric,2)
from customer_shopping_behavior
group by item_purchased 
order by  avg(review_rating) desc
limit 5

--4. compare the average purchase amount between standard and express shipping ?
select shipping_type, round(avg(purchase_amount_usd) ,2)
from customer_shopping_behavior
where shipping_type = 'Express' or shipping_type = 'Standard'
group by shipping_type 

-- 5. do subscribed customers spend more ? compare average spend and total revenue 
-- between subscribers and non subscribers ?

select subscription_status , count(customer_id) as total_customers, avg(purchase_amount_usd) as average_spend,
       sum(purchase_amount_usd) as total_revenue 
from customer_shopping_behavior
group by subscription_status
order by total_revenue , average_spend

-- 6. which 5 products have the highest percentage of purchases with discounts applied ?
SELECT  item_purchased, 
        round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end) /  count(*) , 2) as purchase_percentage
FROM customer_shopping_behavior
GROUP BY item_purchased 
ORDER BY purchase_percentage DESC
LIMIT 5

-- 7. segment customers into new , returning and local based on their total number of previous purchases and show the
--    count of each segment 
with customer_type as (
    select customer_id , previous_purchases , (case when previous_purchases = 1 then 'new'
	                                               when previous_purchases between 2 and 10 then 'returning'
												   else 'loyal'
												   end) as customer_segment
    from customer_shopping_behavior
)
select customer_segment , count(*) as number_of_customers
from customer_type 
group by customer_segment 


-- 8. what are the top 3 most purchased products within each category ?
with itemCounts as (
     select category , item_purchased , count(customer_id) as total_orders ,
	        row_number() over( partition by category order by count(customer_id) desc )as item_rank 
	 from customer_shopping_behavior
	 group by category , item_purchased 
)
select item_rank , category , item_purchased , total_orders
from itemCounts
where item_rank <= 3

-- 9. are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe ? 
select subscription_status , count(customer_id) as repeat_buyers 
from customer_shopping_behavior
where previous_purchases > 5 
group by subscription_status


-- 10. what is the revenue contribution of each age group 
select age_group , sum(purchase_amount_usd) as total_revenue
from customer_shopping_behavior
group by age_group 
order by total_revenue desc



